Cargo.lock
Cargo.toml
src/commands/farm.rs
src/main.rs
src/utils.rs

This PR enables to option to farm in verbose or quiet mode, via verbose flag. And also:
- updates tracing from our fork to original repo
- moves logging related part to utils
- and small fixes

Quiet mode

---

Cargo.lock
Cargo.toml
src/commands.rs
src/commands/farm.rs
src/commands/wipe.rs
src/config.rs
src/main.rs
src/utils.rs

Closes #22 
**When in progress:**
**When finished:**
@i1i1 please check the `TODO`s in the code.

Farm progress bar

---

.github/workflows/release.yml

[WIP] Fix Releases.yml

---

Cargo.toml
src/commands/farm.rs
src/commands/info.rs
src/commands/init.rs
src/config.rs
src/utils.rs

This pr fixes 2 things:
- improves performance of dev builds (so that we won't wait half a minute on demo for node setup :D)
- Adds more typing for the `init` function and simplify things by inlining most of utils function

Some code improvements to `init` function

---

src/commands/farm.rs
src/config.rs

parsing the config for wipe should not validate the config

---

Cargo.lock
Cargo.toml
src/commands/farm.rs
src/commands/init.rs
src/config.rs
src/main.rs
src/utils.rs

Node starts, farming starts. Seems to be working :) 
We can test it more thoroughly on Monday
Happy thanksgiving!

Implement tests and support gemini-3a

---

.github/workflows/ci-tests.yml
Cargo.lock
Cargo.toml
src/commands/farm.rs

- Updates the CLI according to the SDK changes
- updates workflow

update sdk dependency and also workflows

---

src/main.rs

Tried `[skip ci]` for the first time. Glad that it works, it will prove useful in the future for sure. 
That's why tests did not run but I ran them all on my local machine and this code change is quite small. We should be good to go without github CI for this PR

Enable force close

---

.github/workflows/ci-tests.yml
Cargo.lock
Cargo.toml
src/commands/farm.rs
src/commands/init.rs
src/config.rs
src/main.rs
src/utils.rs

@i1i1 I've copied the DSN listen address from monorepo as suggested, please double check everything because I'm not familiar with DSN yet

default dsn

---

Cargo.lock
Cargo.toml
src/config.rs

Will update the `min_plot_size` later. Let's push a release!

new chain spec

---

src/commands/farm.rs
src/commands/wipe.rs
src/config.rs

Fixes #77 
Also fixes regression for toml config serialization.

Fix farmed blocks issue

---

src/commands/farm.rs
src/commands/info.rs
src/summary.rs
src/utils.rs

Refactored summary, now it's more Rusty :)
Also, I think, this will fix the bug Wei has faced. 
Lastly, removes the unnecessary log directive (was required before, not anymore)

fix summary bug & remove unnecessary directive

---

src/config.rs

better error handling

---

.github/workflows/ci-tests.yml
rustfmt.toml
src/commands/farm.rs
src/commands/init.rs
src/commands/wipe.rs
src/config.rs
src/main.rs
src/summary.rs
src/utils.rs

@nazar-pc , this `exclude` operation on matrices may be useful in monorepo as well maybe?

updates workflow and adds custom formatting for rustfmt

---

Cargo.lock
Cargo.toml
src/commands/farm.rs
src/commands/wipe.rs
src/config.rs

Checked. Even though we removed some config fields it seem to work for current config, so no need to write migrations.
Fixes #86
New progress bars for syncing and plotting look like this:
[![asciicast](https://asciinema.org/a/PwJv7vXtX5z742DZkoUIRAG0o.svg)](https://asciinema.org/a/PwJv7vXtX5z742DZkoUIRAG0o)

Update sdk version and progress bars

---

Cargo.lock
Cargo.toml
src/commands/farm.rs
src/commands/init.rs
src/config.rs
src/utils.rs

Gemini3b support

---

Cargo.lock
Cargo.toml
src/config.rs

Pulling changes from https://github.com/subspace/subspace-sdk/pull/106

Inline sdk configs

---

Cargo.toml

will publish a release after this

bump version to 0.1.5

---

Cargo.lock
Cargo.toml
rust-toolchain.toml

Updated rust nightly as in monorepo,
also fixed dependabot warnings for outdated crates

update dependencies and rust

---

Cargo.lock
Cargo.toml
clippy.toml
src/commands/farm.rs
src/commands/init.rs
src/config.rs
src/main.rs
src/utils.rs

I've tested it, syncing works!
Will run another test in the background for and leave it open for tonight.
Don't enable auto merge, since the revision for SDK points to a branch, which will be deleted after SDK PR merges. So I will update the revision once more when SDK merge happens for the gemini3c pr. 
Other than that, it should be good to go!

Prepare gemini 3c

---

Cargo.lock
Cargo.toml
src/config.rs
src/utils.rs

solves #105 
and updates monorepo/sdk

Provider storage support

---

Cargo.lock
Cargo.toml
src/commands/farm.rs
src/commands/init.rs
src/config.rs
src/utils.rs

- updates dependencies (both sdk, and other ones)
- simplified plotting progress bar code and made it more similar to syncing progress bar for consistency
- added authority to dev setting
- now, we are listing chain options during init step, so users won't be confused:
- because I confused myself with `dev` and `devnet` :D 
- if I got confused, I'm sure users will too hehe

Update Dependencies, and small optimizations

---

Cargo.lock
Cargo.toml

upgrade version for release

---

src/commands/farm.rs

update the current line instead of appending new line

---

Cargo.lock
Cargo.toml
src/config.rs
src/main.rs

Closes #124. Also sets implementation version for telemetry.

Minor updates

---

.cargo/config.toml
.github/workflows/ci-tests.yml
.github/workflows/release.yml
.github/workflows/rustdoc.yml
Cargo.lock
Cargo.toml
src/commands/farm.rs
src/commands/init.rs
src/config.rs
src/main.rs
src/utils.rs

This PR:
- updates sdk to the latest version -> there are breaking changes, so I needed to:
- overhaul to farmer function -> while I'm at it, I made subscriptions more safer. I was occasionally getting some errors related to subscriptions. I think these will be resolved :) -> solves #132 
I will submit another PR for addressing more smaller issues
After merging these 2 PR's, I will also create a branch for supporting `gemini-3c`.

Update sdk & overhaul farmer

---

Cargo.lock
Cargo.toml
src/utils.rs

This PR fixes the executable name bug. Quite minor bug, did not open an issue for it

fix executable name and bump version

---

src/commands/wipe.rs
src/main.rs
src/utils.rs

farmer and node flags for wipe command

---

Cargo.lock
Cargo.toml
src/commands/farm.rs
src/commands/init.rs

fix farmer silent exit

---

.github/workflows/Entitlements.plist
.github/workflows/release.yml

After this, we will have proper macos signing. I did test it via manual dispatch (downloaded the executables, everything is fine 🥳 )

Fix macos signing

---

.github/workflows/ci-tests.yml
.github/workflows/release.yml
.github/workflows/rustdoc.yml

I thought I had fixed this, but seems like this commit got lost in between, weird...

fix clang workflow

---

Cargo.lock
Cargo.toml
src/commands/info.rs
src/commands/wipe.rs
src/config.rs
src/main.rs
src/summary.rs
src/utils.rs

This PR:
- revamps wipe and info command w.r.t summary changes
- adds tokio console tracing

wipe and info revamp, add console tracing

---

Cargo.lock
Cargo.toml
src/commands/farm.rs
src/summary.rs

Summary bug fix

---

Cargo.lock
Cargo.toml
src/commands/info.rs
src/commands/wipe.rs
src/config.rs
src/main.rs

Do not be fooled by the first part, there is no bug :)
We have a baby TUI :)

Arrow keys

---

Cargo.lock
Cargo.toml
src/main.rs
src/utils.rs

command for opening logs in default file browser w.r.t OS

open log folder with default file browser

---

.github/workflows/release.yml

This PR fixes an issue with outdated Linux packages
- runs an apt-get update then apt-get install of packages

fix actions pipeline linux packages

---

src/commands/farm.rs
src/main.rs
src/utils.rs

disable rotation with argument

---

.github/workflows/release-self-hosted.yml

This PR creates self-hosted runners for the subspace cli repository that will run jobs on the following:
- Linux X86_64
- Mac ARM64
- Windows x86_64
Cross compilation of AARCH64 linux will be done on x86_64.

create actions workflow self-hosted runner

---

Cargo.lock
Cargo.toml
rust-toolchain.toml
src/commands/farm.rs
src/commands/init.rs
src/commands/wipe.rs
src/config.rs
src/main.rs

This is companion PR of https://github.com/subspace/subspace-sdk/pull/197

Update cli to be in sync with latest version of sdk

---

Cargo.lock
Cargo.toml
src/config.rs
src/tests.rs

Update to subspace-sdk with updated Gemini 3e chain spec.

update gemini-3e chain spec

---

Cargo.lock
Cargo.toml
src/commands/farm.rs
src/summary.rs

Earned SSC is now shown in the correct units.
Fixes #215

Display earned SSC in correct unit

---

Cargo.lock
Cargo.toml
src/commands/farm.rs
src/commands/init.rs
src/commands/wipe.rs
src/config.rs
src/main.rs
src/tests.rs
src/utils.rs

Update pulsar to sdk commit containing gemini-3f-2023-aug-21 snapshot. 
Renaming of `Plot` to `Farm`
Wipe the farmer and node before using this release.

update pulsar to gemini-3f-2023-aug-21 snapshot

---

Cargo.lock
Cargo.toml

Minor update to CLI with changes in sdk in segment headers request handler incorporated

Upgrade sdk with changes in segment headers request handler

---

Cargo.lock
Cargo.toml

This PR updates pulsar to latest version of SDK with changes from gemini-3f-2023-aug-22 snapshot.

Upgrade to sdk with changes from gemini-3f-2023-aug-22 snapshot

---

Cargo.lock
Cargo.toml
src/commands/farm.rs
src/config.rs

Upgrade to subspace-sdk with changes from [gemini-3f-2023-aug-25-2 snapshot](https://github.com/subspace/subspace/releases/tag/gemini-3f-2023-aug-25-2).

Upgrade to sdk with changes from gemini-3f-2023-aug-25-2 snapshot

---

Cargo.lock
Cargo.toml

This PR updates CLI to use newer version of SDK up-to-date with gemini-3f-aug-31 snapshot.

Update to august 31st snapshot

---

Cargo.lock
Cargo.toml

This PR updates pulsar to use new SDK updated with `gemini-3f-sep-13-2` monorepo snapshot.

Update to gemini-3f-sep-13-2

---

.github/workflows/ci-tests.yml

Remove merge queue from the ci test workflow

remove merge queue

---

Cargo.lock
Cargo.toml

This PR updates pulsar to sdk updated with `gemini-3f-2023-sep-21` monorepo snapshot.

Update pulsar to sdk updated with gemini-3f-2023-sep-21 snapshot

---

Cargo.lock
Cargo.toml

This PR updates pulsar to sdk up-to-date with gemini-3f-2023-sep-24 [snapshot](https://github.com/subspace/subspace/releases/tag/gemini-3f-2023-sep-25)

Update pulsar with gemini-3f-2023-sep-25 snapshot

---

Cargo.lock
Cargo.toml

Update pulsar to use sdk up-to-date with `gemini-3f-2023-oct-1` snapshot

Update pulsar to use sdk up-to-date with gemini-3f-2023-oct-1 snapshot

---

Cargo.lock
Cargo.toml

Update pulsar to sdk up-to-date with `gemini-3f-2023-oct-4`

Update pulsar to sdk up-to-date with gemini-3f-2023-oct-4 release

---

Cargo.lock
Cargo.toml

This PR updates pulsar with sdk updated with monorepo `gemini-3f-2023-oct-6`

Update pulsar with gemini-3f-2023-oct-6 snapshot

---

Cargo.lock
Cargo.toml

This PR updates pulsar to `gemini-3g-2023-dec-22` snapshot. Only changes in the codebase are git reference.

Update pulsar to `gemini-3g-2023-dec-22` snapshot

---

.github/workflows/ci-tests.yml
.github/workflows/release.yml
Cargo.lock
Cargo.toml

PR updates CI workflows for numa support depedencies.
- ref: https://github.com/subspace/subspace/pull/2374/commits/56e888fe5e0fc7abd3ce3cd28511f04b6ebc656f

CI fixes for latest dependencies based on monorepo

---

.github/workflows/ci-tests.yml

minor CI fix:
- Fix runs-all keys in matrix os.

fix matrix OS

---

.github/workflows/ci-tests.yml
.github/workflows/release.yml

fixes https://github.com/subspace/pulsar/pull/281/files
PR updates CI workflows to be align with dependencies in https://github.com/subspace/subspace/commit/56e888fe5e0fc7abd3ce3cd28511f04b6ebc656f

add automake and hwloc for macOS and support numa CI workflow

---

.github/workflows/release.yml

- fix production build targets

Ci fix for pulsar build production targets

---

README.md

This PR (considered all feedbacks from [PR](https://github.com/subspace/pulsar/pull/295)) is to replace the installation steps with homebrew for macOS in README.
There was an issue: https://github.com/subspace/pulsar/issues/270 which is resolved with https://github.com/subspace/homebrew-pulsar/pull/1.

Updated macOS binary installation with homebrew

---

Cargo.lock
pulsar/Cargo.toml

This PR updates minor version for gemini-3h. New version is `v0.8.0`

Bump minor version for gemini-3h
