subspace/pulsar

.github/workflows/release.yml, Cargo.toml
I've tested it without the signing part (it is commented out in the yml file).
Works! If you want to try it out, check my fork -> https://github.com/ozgunozerk/subspace-cli-workflow/actions/runs/3470276715 (scroll down to see artifacts)
We have to test it with signing as well. @achiurizo can you add the respective secrets to the repo please?
After we merge this, I'll update the readme on how to download the executables and run them.
=> release workflow - without signing

.github/workflows/ci-tests.yml, Cargo.lock, Cargo.toml, rust-toolchain.toml, src/commands/farm.rs, src/commands/init.rs, src/commands/wipe.rs, src/config.rs, src/summary.rs
This pr:
- uses all the fields in `settings.toml` now in node configuration (except the `execution`, for that, waiting on SDK)
- updates nightly version, `cargo doc` command now works 100% fine
- optimizes CI, so that macOS won't occasionally fail because of `protoc`
- gets rid of `gemini-2a`
Let's try to build executables after this PR, and if it succeeds, I'll update the readme accordingly for downloading instructions
=> Node settings

src/commands/init.rs, src/config.rs, src/utils.rs
This will allow us to check the validity of the config at each parse operation. So that, possible erroneous scenarios would be prevented:
1. user creates a valid config via `init` command
2. then modifies the config as they please (but it's not valid anymore.. Oh dear user! What have you done?!)
3. farm function crashes with a weird message, because config is not valid
4. many other things crash too, it's chaos now
=> config validity checks at each parsing

src/config.rs
`SinglePlotDisk::new()` is handling the folder creation via `create_dir_all()`, no need to validate if the given directory exists while parsing the config.
=> no need to validate plot dir

Cargo.lock, Cargo.toml
`init` was still showing `v0.1.0`, let's fix that :)
=> update version to 0.1.3

.github/workflows/ci-tests.yml, Cargo.lock, Cargo.toml
After fixing the weird windows bug, I got another one (link error). Fortunately was able to solve that tonight. 
Ignore the ugly commits, will squash merge them anyway.
Manually triggered tests have passed: https://github.com/subspace/subspace-cli/actions/runs/3743712339/jobs/6356202788
will merge this as soon as it's approved
=> Wasmtime downgrade fix

src/commands/farm.rs, src/commands/wipe.rs, src/config.rs, src/utils.rs
This PR:
- gets rid of the `unwrap()`s in the code (excluding tests)
- relaxes the wipe criteria, so even when there is a breaking change, the `wipe` command will attempt to remove the plots in the default directory. And prints a nice warning message as:
```
"could not read your config. There could have been a breaking change, or you may \
have an ill-formed config file. Wipe will continue... \n",
"However, if you have set a custom location for your plots, you will need to \
manually delete your plots!"
```
=> Clear unwraps

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, CODE_OF_CONDUCT.md
Please review thoroughly @achiurizo @jfrank-summit .
For the code of conduct, there was this part:
```
Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by contacting us anonymously through [this form](https://goo.gl/forms/chVYUnA4bP70WGsL2). All complaints will be reviewed and investigated and will result in a response that is deemed necessary and appropriate to the circumstances. The project team is obligated to maintain confidentiality with regard to the reporter of an incident.
Project maintainers who do not follow or enforce the Code of Conduct in good faith may face temporary or permanent repercussions as determined by other members of the project's leadership.
If you are unsure whether an incident is a violation, or whether the space where the …
```
=> Issue template and code of conduct

src/config.rs
There is a problem with `subscape-cli init` if there is no `.config` path in your `$HOME`, in this case, you will get such error:
```
Error: could not create the directory, because: No such file or directory (os error 2)
```
This happens because `create_dir` can't produce recursive directories creation so this command will fail.
So, there was changed:
- `create_dir` to `create_dir_all` in the `create_config` step. 
- `AlreadyExists` error check was dropped because `create_dir_all` don't raise this error.
- Added `config_path` to error logging for debug purposes
=> Recursive config path creation

.github/ISSUE_TEMPLATE/bug_report.yml, src/commands/wipe.rs
- improves bug issue template via allowing multiple selects for the platforms
- simplifies error message for wipe command in case of `subspace-cli` folder is missing
=> update error message and improve bug issue template

Cargo.lock, Cargo.toml, src/commands/farm.rs, src/commands/info.rs, src/commands/init.rs, src/commands/wipe.rs, src/config.rs, src/main.rs, src/summary.rs, src/utils.rs
Simplifies the config.
Don't inspect commit by commit, since they do not make sense and I'll squash merge anyway
closes #117
=> Config revamp

.github/workflows/release.yml, Cargo.lock, Cargo.toml, src/commands/farm.rs, src/config.rs
This PR:
- optimizes releases for linux with v2 and v3 as done in monorepo
- fixes a small bug about telemetry version
- adds support for gemini3c again to main branch. 
(I will make a `dev` branch to support up-to-date latest main/master from monorepo/sdk)
=> support gemini3c again

src/commands/init.rs, src/main.rs, src/utils.rs
This PR:
- adds `-V` and `--version` flags so users can get the version even if they change the name of the executable
- gets the executable name from `std::env`
- crafts the `subspace-cli farm` command dynamically w.r.t the current directory (if current directory is where the executable is located, only `./subspace-cli farm` is generated. If not, `/path/to/executable/subspace-cli farm` is generated
@ImmaZoni tagging you, so that you can change the docs accordingly when we have a new release
closes #146
=> Version command

.github/workflows/release-notifier.yml
This GitHub Action will notify our Discord community using a provided webhook URL (provided as a GitHub Secret). We are using a custom action instead of the native GitHub webhook because of the lack of customization in messaging and lack of control regarding the notification of a pre-release or latest release. The default webhook will notify of all releases, regardless of the release type.
This action works with the following logic:
It is triggered under two circumstances:
- The successful completion of our `release` workflow.
- A manual trigger.
We will walk through the pathway for each trigger separately for clarity.
This pathway assumes the release being created is being marked as latest and is not a pre-release.
1. The `release` workflow completes with no errors, sending the `success` …
=> Implement Discord Webhook for Release Notification

Cargo.lock, Cargo.toml, rust-toolchain.toml, src/commands/farm.rs, src/summary.rs
closes #163 
This PR:
- adds error propagation to subscriptions (tokio tasks)
- overhauls summary, so that we are now able to track:
- vote count
- rewards earned
- blocks farmed
Because of `summary` changes, this will be a breaking change.
I'll implement the logic for wiping summary in the next pr, since i will make more changes to `wipe` and `info`
=> Subscription error propagating

.github/workflows/release-notifier.yml, .github/workflows/release.yml, Cargo.toml
This PR:
- fixes the new bug emerged for `aarch64 linux` platform on compilation
- improves the discord release notifier workflow, so that, it won't be triggered when the `release` workflow is run manually. We don't want to inform discord users by sending false-positives while we are performing test runs on the `release` workflow.
=> fix release and discord release notifier workflows

src/commands/init.rs, src/tests.rs, src/utils.rs
Closes #174 and closes #173 
This PR:
- makes node directory customizable in `init` step
- when user supplies a path for `node` or `plot` directory, and if that path is not created yet, the program now prompts the user for creation of this directory
=> implement node and plot improvements

.github/workflows/release.yml
Until this issue gets fixed: https://github.com/tokio-rs/console/issues/299,
console-subscriber flag is disabled for the release build, which is causing `clock skew` issue.
closes #189
=> disable console-subscriber

Cargo.lock, Cargo.toml, src/commands/init.rs
This PR adds a new feature, which is having the ability to generate public key and mnemonic in the CLI.
Closes #199 
New flow for the farmer address during `init` step:
1. CLI asks the the user if they have an existing public key
2. if not, a new prompt for if user wants to generate a public key
3. display the mnemonic, show the proper messages, then redact it, and prompt user to prove if they stored the mnemonic (ask random words from the 12 word mnemonic)
4. if users passes the test, display the public key, and set it
Redacting the mnemonic was important for this setup, and I'm using crossterm to handle edge cases here. Code should be safe for all sized terminals for redacting the mnemonic completely without clearing other parts of the terminal.
=> key generation if user does not have a public key beforehand

Cargo.lock, Cargo.toml, src/commands/farm.rs, src/summary.rs, src/tests.rs
Previously,`update()` method for `Summary`:
1. acquire lock for parsing the summary
2. release that lock
3. acquire a new lock for writing to summary
4. write, then release the lock
Also, it was moving the cursor (seeking) to the beginning of the file, and then flushes. 
I have fixed those 2 things in this PR. 
Also, yanking the version, since I'll publish a new version (we have key generation on CLI right now, and this small bug fix)
Closes #202 
Note: will squash commit
=> Summary bug

.github/workflows/release.yml
Release workflow is no longer working for aarch linux. 
This will hopefully fix it
=> change v3 to skylake

.github/workflows/release-notifier.yml
This PR introduces an enhancement to our release notification process. Upon the successful release of a new version, an additional step in our GitHub Actions workflow will now automatically create an issue in the subspace/subspace-docs repository. This issue will contain details of the new release and will serve as a prompt to update the documentation accordingly.
While this adds a layer of automation to our process, it is considered a temporary measure. Our ultimate goal is to achieve full automation of documentation updates in line with new releases. Until we reach that point, this solution will help to ensure that our documentation stays up-to-date with the latest released versions.
=> Add Step to Notify `subspace-docs` Repository of New Releases

.cargo/config.toml, src/commands/farm.rs
Closes #209 
Basically, the update logic for `last_processed_block_num` was incorrect. It won't be possible to `last_processed_block_num` to surpass `last_retrieved_block_num` anymore.
I also fixed the following small things:
- variable namings were not descriptive enough, making the code harder to understand
- a minor logic error in the `not_yet_processed_blocks`, returning the last processed block also in the stream
- now, handling the error case where `last_processed_block_num` is greater than `last_retrieved_block_num`, and provides a good solution to the user
also thanks to @jim-counter for testing these on different platforms!
=> fixing parallel stream update logic, and some minor things like namings

.github/workflows/ci-tests.yml, .github/workflows/release.yml
This PR introduces the use of self hosted runners for the repository.
- supports Ubuntu-22.04, macOS-12 and Windows-server-2022 runners
=> CI update to use GH self-hosted runners

.github/workflows/ci-tests.yml, .github/workflows/release.yml
Reverts subspace/subspace-cli#225
See [comment ](https://github.com/subspace/subspace-cli/pull/225#pullrequestreview-1524139932) from original pull request:
> This PR broke support for GitHub runners and broke executables on Ubuntu 20.04. IMHO most of it must be reverted and our self-hosted runners should "just work" with little to no changes to workflows.
=> Revert "CI update to use GH self-hosted runners"

Cargo.lock, Cargo.toml
This PR references a new version of SDK which has 3 GB of node piece cache. Patch version is updated.
=> Update CLI to use SDK with 3 GB node piece cache

Cargo.lock
Cargo.lock did not update to cli version 0.5.3 in last PR.
=> update cargo.lock to version 0.5.3

.github/workflows/ci-tests.yml, .github/workflows/release.yml, .github/workflows/rustdoc.yml
This PR improves on https://github.com/subspace/subspace-cli/pull/225 and fixes the concerns:
- use cargo stable installed on servers
- removes windows protoc installation for self-hosted runner
- make runners compatible with self-hosted runners and github actions runners
- uses ubuntu-20.04 for backward compatibility with older glibc
=> Self-hosted GitHub Actions runners

.github/workflows/ci-tests.yml, .github/workflows/release.yml, .github/workflows/rustdoc.yml
- This PR introduces merge [queues](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) to the worflows.
=> add merge queue event to ci workflows

.github/workflows/release.yml
- Merge queue should not run on release workflow, this corrects #244
=> Remove merge queue event from release workflow

Cargo.lock, Cargo.toml, rust-toolchain.toml, src/commands/farm.rs, src/commands/init.rs, src/commands/wipe.rs, src/config.rs, src/main.rs, src/tests.rs, src/utils.rs
This PR do following: 
- Use latest SDK containing updates from Gemini 3f snapshot
- Allowing users to run a domain node
- Bump the version to `v0.6.0`
=> Gemini 3f release

Cargo.lock, Cargo.toml
This PR updates pulsar to use SDK updated with gemini-3f-2023-sep-05 monorepo snapshot.
=> Update to gemini-3f-2023-sep-11 subspace sdk version

Cargo.lock, Cargo.toml
This PR updates pulsar to the latest version of the SDK, utilizing the [gemini-3f-2023-oct-03 snapshot](https://github.com/subspace/subspace/releases/tag/gemini-3f-2023-oct-03)
=> Update pulsar with gemini-3f-2023-oct- snapshot

README.md
Greetings everyone!
This PR introduces a Build section to the README file of this repository.
Previously, we utilized binaries from the [releases](https://github.com/subspace/pulsar/releases) page tailored to each operating system.
With the inclusion of this new section, building from the repo should now be error-free.
Also, in addition we can install the `pulsar` CLI using cargo (on the fly) if the latest code is already maintained (pulled) locally.
This reduces the effort of downloading the executable (binary) each time when there is a new release.
=> Added Build & Install (using cargo)

README.md
This PR is to just add a minor change during installation using cargo. So, instead of `cargo run`, execute `cargo build`. And release mode is opted as it generates optimized binary for installation.
=> Minor Fix: Build instead of Run

.cargo/config.toml, Cargo.lock, Cargo.toml, rust-toolchain.toml, src/commands/farm.rs, src/commands/init.rs, src/config.rs, src/tests.rs
This PR updates pulsar to `gemini-3g-2023-nov-21` snapshot. 
First commit makes pulsar generally compatible and up-to-date with `gemini-3g-2023-oct-31`.
Second commit enables sync from dsn via setting a flag while building a node.
Third commit updates pulsar to `gemini-3g-2023-nov-21` release and pulsar version is updated to `v0.7.0`
=> Upgrade to gemini-3g-2023-nov-21 snapshot

Cargo.lock, Cargo.toml, src/commands/farm.rs, src/summary.rs, src/tests.rs
This PR fixes the error encountered during the decoding of the events. And also upgrades to `gemini-3g-2024-jan-08` snapshot.
During the gemini-3g network run, we upgraded the runtime multiple times. During one of the upgrade, we [modified](https://github.com/subspace/subspace/commit/bde438e58bcc2b1242dc5c2d8e88f9965b262bad) `FraudProofProcessed` event. Specifically, adding Option  to the `new_head_receipt_number`  [field](https://github.com/subspace/subspace/commit/bde438e58bcc2b1242dc5c2d8e88f9965b262bad#diff-9f80450addc12cd3b681275c6acb663003edc27c2d8eeeb1f26147df9f8e5bbeR731). This added an extra byte in the encoding of that event after the runtime upgrade.
Since pulsar uses the latest runtime present in the code (and not on-chain runtime for that block) to decode the events, when it …
=> Fix reward error and upgrade to `gemini-3g-2024-jan-08` snapshot

Cargo.lock, Cargo.toml, src/config.rs
This PR enables subspace block relay for `gemini3g` and `devnet`. It enables dsn sync for `devnet` as well. This will fix the syncing issue with pulsar.
=> Enable subspace block relay for `gemini3g` and `devnet`

.github/workflows/ci-tests.yml, .github/workflows/release.yml
switch workflows to use macos-14 operating system as our new self-hosted runners are running this OS version.
closes https://github.com/subspace/infra/issues/251
=> switch CI workflow to macos-14 runners

pulsar/src/config.rs, pulsar/src/main.rs
There were still remnants of "Subspace CLI" to be found which was showing up in telemetry. This PR removes the last remnants.
=> Update "Subspace CLI" to "pulsar" in command info and implementation
